### ISSUE TITLE
temperature-glance | Is it possible to use a camera image as the background?

### ISSUE THREAD

**Issue by xbmcnut** [sharetheloveio/sharethelove.io#52]
Hi there,

Love the look of this one. I'm using 5 x picture-glance cards now but I'd like to see the values from several sensors rather than just an icon. I tried replacing `image:` with `camera_image:` but it threw up an error.

**Comment by isabellaalstrom** [comment]
A camera image is not supported as background in the picture elements card. What you can do is put in a picture element that's as big as the card, that can have camera image, and have that as "background". Read more in the docs:  https://www.home-assistant.io/lovelace/picture-elements/

**Comment by xbmcnut** [comment]
That's a great idea Isabella. I had not thought of that. I'll play around with it. Thanks.

**Comment by xbmcnut** [comment]
![image](https://user-images.githubusercontent.com/1492137/46864031-97518e00-ce75-11e8-99b2-e0e27bdc43fb.png)

Got close to replicating my picture-glance. Can't quite get the camera image to fit properly unfortunately but got close to the result I was looking for.

```
              - type: picture-elements
                image: /local/lovelace/icons/800x480_white.jpg
                elements:
                  - type: image
                    entity: camera.front_porch
                    camera_image: camera.front_porch
                    style:
                      top: 50%
                      left: 50%
                      width: 99%
                      # border: 2px solid black
                      # border-radius: 10%
                  - type: state-label
                    entity: sensor.deadbolt_batteries_front_door
                    tap_action: more-info
                    style:
                      top: 85%
                      left: 18%
                  - type: icon
                    icon: mdi:battery-90
                    tap_action: more-info
                    style:
                      top: 85%
                      left: 10%
                  - type: state-icon
                    tap_action: more-info
                    entity: lock.frontdoor_deadbolt
                    style:
                      top: 85%
                      left: 25%
```
