### ISSUE TITLE
Glance av-remote

### ISSUE THREAD

**Issue by CiquattroFPV** [sharetheloveio/sharethelove.io#72]
I have followed the instruction for setup this glance card.. but I have a blank area when I reload the Lovelace UI.

Can you help me to troubleshoot this issue?

**Comment by CiquattroFPV** [comment]
I have added this to the UI-lovelace.yaml 

```

####################################################
#                                                  #
#              AV Remote Controller                #
#                                                  #
####################################################
    # Title of the view. Will be used as the tooltip for tab icon
  - title: AV Remote
    path: remote
    cards:
    entities:
      - type: glance
        cards: !include /config/remotes/lg.yaml
```


and then I have copied all the contents of the lg.yaml inside the folder /config/remotes/lg.yaml
